### PR TITLE
[changed] added callback for light value updates

### LINKED ISSUE #97: Lights are not updated
**Describe the bug**
Lights are not updating. color does not change

**To Reproduce**
1. add a light
2. changes its properties

### PR DESCRIPTION
**Pull request by sainsay**
fixes #97 

## Screenshots (if appropriate):
https://gfycat.com/ConstantYellowLadybug

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: src/plugin/parsers/light_parser.cpp [hunk 1]
```diff
@@ -117,6 +117,87 @@ namespace wmr
...
+		wmr::LightParser* light_parser = reinterpret_cast<wmr::LightParser*>(client_data);
+
+		MStatus status = MS::kSuccess;
+		MFnLight fn_light(plug.node(), &status);
+		
+		MFnDagNode dagnode = fn_light.parent(0, &status);
+		if (status != MS::kSuccess)
+		{
+			LOGE("Could not get the dag node.");
+			MGlobal::displayError("Error: " + status.errorString());
```
Comment (MeineZ) [inline src/plugin/parsers/light_parser.cpp]: LOGE already automatically logs to the Maya script editor log. ::displayError is unnecessary.

File: src/plugin/parsers/light_parser.cpp [hunk 2]
```diff
@@ -117,6 +117,87 @@ namespace wmr
...
+			{
+				return;
+			}
+		}
+
+		switch (api_type)
+		{
+		case MFn::Type::kAmbientLight:
+			LOGE("Wisp does not support ambient light, user tried to add ambient light.");
+			//cry, crash, burn!!
```
Comment (MeineZ) [inline src/plugin/parsers/light_parser.cpp]: Unprofessional comment 😉

**Review by MeineZ — CHANGES_REQUESTED** [review]

**Review by MeineZ — APPROVED** [review]
